FROM ubuntu:16.04 AS base

ENV HADOOP_HOME /opt/hadoop
ENV SPARK_HOME /opt/spark
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-wheel \
    openjdk-8-jdk \
    wget

RUN wget https://www-eu.apache.org/dist/spark/spark-2.3.2/spark-2.3.2-bin-hadoop2.7.tgz && \
    tar -xzf spark-2.3.2-bin-hadoop2.7.tgz && \
    mv spark-2.3.2-bin-hadoop2.7 $SPARK_HOME

RUN pip3 install jupyter pyspark pandas matplotlib seaborn sklearn

WORKDIR /app

COPY . /app

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt install -y supervisor

RUN echo
